sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - main # build main branch only
before_script:
  - git config --global user.name "wanyvic"
  - git config --global user.email q873040807@gmail.com
  - sed -i'' "s~git@github.com:wanyvic/wanyvic.github.io.git~https://${GH_TOKEN}@github.com/wanyvic/wanyvic.github.io.git~" _config.yml
script:
  - hexo clean
  - hexo generate
after_success:
  - hexo deploy
